### ISSUE TITLE
JavaScript-30

### ISSUE THREAD

**Issue by LiuL0703** [LiuL0703/task#4]
# 01
## 关于CSS中的transitionend事件

MDN：transitionend 事件会在 CSS transition 结束后触发. 当transition完成前移除transition时，比如移除css的transition-property 属性，事件将不会被触发.如在transition完成前设置 display: none，事件同样不会被触发.

**Comment by LiuL0703** [comment]
# 03
## CSS自定义属性
带有前缀 -- 的属性名，比如 --example--name，表示的是带有值的自定义属性，其可以通过 var 函数在全文档范围内复用的。
#### 语法：
```css
:root {
  --first-color: #488cff;
  --second-color: #ffff8c;
}

#firstParagraph {
  background-color: var(--first-color);
  color: var(--second-color);
}
```

## filter
CSS滤镜（filter）属提供的图形特效，像模糊，锐化或元素变色。过滤器通常被用于调整图片，背景和边界的渲染。 CSS标准里包含了一些已实现预定义效果的函数。你也可以参考一个SVG滤镜，通过一个URL链接到SVG滤镜元素(SVG filter element)
例如：
```css
filter: blur(5px)  // 对图像采取高斯模糊
```
